### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode characters

### ISSUE THREAD

**Issue by thorne51** [m-wrzr/populartimes#10]
Hello,

I tried running your example request and got the error mentioned above. Here is my entire `test.py`:

```python
import populartimes

mylist = populartimes.get("api-key", ["bar"], (48.132986, 11.566126), (48.142199, 11.580047))
print(mylist);
```

Full output as follows:
```
$ py test.py
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    print(mylist);
  File "C:\Users\chris\AppData\Local\Programs\Python\Python35-32\lib\encodings\cp437.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 121875-121880: character maps to <undefined>
```

**Comment by m-wrzr** [comment]
Seems like a problem with your local encoding. It should be UTF-8. Try adding
`# -*- coding: utf-8 -*-
`
to the start of your script or check your terminal/IDE encoding.
