### ISSUE TITLE
ssl.SSLError: [SSL] internal error

### ISSUE THREAD

**Issue by AvaiyaSoftware** [m-wrzr/populartimes#103]
ssl.SSLError: [SSL] internal error after deployment of my app.

`2021-03-10T03:42:20.589572+00:00 app[web.1]: ERROR:api:Exception on /placeId/ChIJgUbEo8cfqokR5lP9_Wh_DaM [GET]
2021-03-10T03:42:20.589573+00:00 app[web.1]: Traceback (most recent call last):
2021-03-10T03:42:20.589574+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/urllib/request.py", line 1349, in do_open
2021-03-10T03:42:20.589574+00:00 app[web.1]: encode_chunked=req.has_header('Transfer-encoding'))
2021-03-10T03:42:20.589575+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/http/client.py", line 1287, in request
2021-03-10T03:42:20.589575+00:00 app[web.1]: self._send_request(method, url, body, headers, encode_chunked)
2021-03-10T03:42:20.589575+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/http/client.py", line 1333, in _send_request
2021-03-10T03:42:20.589576+00:00 app[web.1]: self.endheaders(body, encode_chunked=encode_chunked)
2021-03-10T03:42:20.589576+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/http/client.py", line 1282, in endheaders
2021-03-10T03:42:20.589576+00:00 app[web.1]: self._send_output(message_body, encode_chunked=encode_chunked)
2021-03-10T03:42:20.589577+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/http/client.py", line 1042, in _send_output
2021-03-10T03:42:20.589577+00:00 app[web.1]: self.send(msg)
2021-03-10T03:42:20.589578+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/http/client.py", line 980, in send
2021-03-10T03:42:20.589578+00:00 app[web.1]: self.connect()
2021-03-10T03:42:20.589578+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/http/client.py", line 1448, in connect
2021-03-10T03:42:20.589578+00:00 app[web.1]: server_hostname=server_hostname)
2021-03-10T03:42:20.589578+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/ssl.py", line 407, in wrap_socket
2021-03-10T03:42:20.589579+00:00 app[web.1]: _context=self, _session=session)
2021-03-10T03:42:20.589579+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/ssl.py", line 817, in __init__
2021-03-10T03:42:20.589579+00:00 app[web.1]: self.do_handshake()
2021-03-10T03:42:20.589579+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/ssl.py", line 1077, in do_handshake
2021-03-10T03:42:20.589580+00:00 app[web.1]: self._sslobj.do_handshake()
2021-03-10T03:42:20.589580+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/ssl.py", line 689, in do_handshake

2021-03-10T03:42:20.589582+00:00 app[web.1]: self._sslobj.do_handshake()
2021-03-10T03:42:20.589582+00:00 app[web.1]: ssl.SSLError: [SSL] internal error (_ssl.c:852)

2021-03-10T03:42:20.589583+00:00 app[web.1]: 
2021-03-10T03:42:20.589583+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2021-03-10T03:42:20.589583+00:00 app[web.1]: 
2021-03-10T03:42:20.589583+00:00 app[web.1]: Traceback (most recent call last):
2021-03-10T03:42:20.589593+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
2021-03-10T03:42:20.589593+00:00 app[web.1]: response = self.full_dispatch_request()
2021-03-10T03:42:20.589594+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
2021-03-10T03:42:20.589594+00:00 app[web.1]: rv = self.handle_user_exception(e)
2021-03-10T03:42:20.589594+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask_cors/extension.py", line 165, in wrapped_function
2021-03-10T03:42:20.589595+00:00 app[web.1]: return cors_after_request(app.make_response(f(*args, **kwargs)))
2021-03-10T03:42:20.589595+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
2021-03-10T03:42:20.589595+00:00 app[web.1]: reraise(exc_type, exc_value, tb)
2021-03-10T03:42:20.589595+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
2021-03-10T03:42:20.589596+00:00 app[web.1]: raise value
2021-03-10T03:42:20.589596+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
2021-03-10T03:42:20.589596+00:00 app[web.1]: rv = self.dispatch_request()
2021-03-10T03:42:20.589597+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
2021-03-10T03:42:20.589597+00:00 app[web.1]: return self.view_functions[rule.endpoint](**req.view_args)
2021-03-10T03:42:20.589597+00:00 app[web.1]: File "/app/api.py", line 22, in index
2021-03-10T03:42:20.589598+00:00 app[web.1]: data = populartimes.get_id(API_KEY, place_Id)
2021-03-10T03:42:20.589598+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/populartimes/__init__.py", line 56, in get_id
2021-03-10T03:42:20.589598+00:00 app[web.1]: return get_populartimes(api_key, place_id)
2021-03-10T03:42:20.589598+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/populartimes/crawler.py", line 441, in get_populartimes
2021-03-10T03:42:20.589598+00:00 app[web.1]: return get_populartimes_by_detail(api_key, detail)
2021-03-10T03:42:20.589599+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/populartimes/crawler.py", line 456, in get_populartimes_by_detail
2021-03-10T03:42:20.589599+00:00 app[web.1]: detail["name"], address
2021-03-10T03:42:20.589599+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/populartimes/crawler.py", line 366, in get_populartimes_from_search
2021-03-10T03:42:20.589600+00:00 app[web.1]: context=gcontext)
2021-03-10T03:42:20.589600+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/urllib/request.py", line 223, in urlopen
2021-03-10T03:42:20.589600+00:00 app[web.1]: return opener.open(url, data, timeout)
2021-03-10T03:42:20.589600+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/urllib/request.py", line 526, in open
2021-03-10T03:42:20.589601+00:00 app[web.1]: response = self._open(req, data)
2021-03-10T03:42:20.589601+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/urllib/request.py", line 544, in _open
2021-03-10T03:42:20.589601+00:00 app[web.1]: '_open', req)
2021-03-10T03:42:20.589601+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/urllib/request.py", line 504, in _call_chain
2021-03-10T03:42:20.589601+00:00 app[web.1]: result = func(*args)
2021-03-10T03:42:20.589602+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/urllib/request.py", line 1392, in https_open
2021-03-10T03:42:20.589602+00:00 app[web.1]: context=self._context, check_hostname=self._check_hostname)
2021-03-10T03:42:20.589602+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/urllib/request.py", line 1351, in do_open

2021-03-10T03:42:20.589602+00:00 app[web.1]: raise URLError(err)
2021-03-10T03:42:20.589611+00:00 app[web.1]: urllib.error.URLError: <urlopen error [SSL] internal error (_ssl.c:852)>`

**Comment by m-wrzr** [comment]
Do you have this error only for specific places or it is general?

Also can you tell me which version of urllib3 you're using?

**Comment by AvaiyaSoftware** [comment]
@m-wrzr  urllib3==1.26.3

**Comment by m-wrzr** [comment]
That should be fine, maybe you can check your `flask` or `cors` configuration for ssl conflicts or sth. similar.

**Comment by gabbycampos** [comment]
I am having the same error. Were you able to solve this error?

**Comment by gabbycampos** [comment]
My error is for all places when searching on the Heroku platform. Works fine on the local server.
