### ISSUE TITLE
populartimes.get does not work anymore, even with your example

### ISSUE THREAD

**Issue by raffie-** [m-wrzr/populartimes#34]
populartimes.get function does not work anymore.

>>populartimes.get(API_KEY9, ["bar"], (48.132986, 11.566126), (48.142199, 11.580047))
Exception in thread Thread-41:
Traceback (most recent call last):
  File "C:\Anaconda3\envs\spider\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Anaconda3\envs\spider\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Anaconda3\envs\spider\lib\site-packages\populartimes\crawler.py", line 130, in worker_detail
    get_detail(item)
  File "C:\Anaconda3\envs\spider\lib\site-packages\populartimes\crawler.py", line 174, in get_detail
    popularity, rating, rating_n = get_populartimes(searchterm)
  File "C:\Anaconda3\envs\spider\lib\site-packages\populartimes\crawler.py", line 237, in get_populartimes
    jdata = json.loads(data)["d"]
  File "C:\Anaconda3\envs\spider\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Anaconda3\envs\spider\lib\json\decoder.py", line 342, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 10910 (char 10909)

Exception in thread Thread-32:
Traceback (most recent call last):
  File "C:\Anaconda3\envs\spider\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Anaconda3\envs\spider\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Anaconda3\envs\spider\lib\site-packages\populartimes\crawler.py", line 130, in worker_detail
    get_detail(item)
  File "C:\Anaconda3\envs\spider\lib\site-packages\populartimes\crawler.py", line 174, in get_detail
    popularity, rating, rating_n = get_populartimes(searchterm)
  File "C:\Anaconda3\envs\spider\lib\site-packages\populartimes\crawler.py", line 237, in get_populartimes
    jdata = json.loads(data)["d"]
  File "C:\Anaconda3\envs\spider\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Anaconda3\envs\spider\lib\json\decoder.py", line 342, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 25613 (char 25612)

Exception in thread Thread-46:
Traceback (most recent call last):
  File "C:\Anaconda3\envs\spider\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Anaconda3\envs\spider\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Anaconda3\envs\spider\lib\site-packages\populartimes\crawler.py", line 130, in worker_detail
    get_detail(item)
  File "C:\Anaconda3\envs\spider\lib\site-packages\populartimes\crawler.py", line 199, in get_detail
    _, _, _, current_popularity = get_current_popularity(place_identifier)
  File "C:\Anaconda3\envs\spider\lib\site-packages\populartimes\crawler.py", line 295, in get_current_popularity
    jdata = json.loads(data)["d"]
  File "C:\Anaconda3\envs\spider\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Anaconda3\envs\spider\lib\json\decoder.py", line 342, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 21583 (char 21582)

Strange because it worked 3 days ago (3rd April 2018).

populartimes.get_id() still works though

**Comment by YoshidaTakahiro3** [comment]
Dear m-wrzr,
I also face the same problem above.  

Thank you very very much for your great contributions.
Takahiro

**Comment by m-wrzr** [comment]
Hey @raffie- 
is it working again for you after the latest update?

**Comment by Moyaga** [comment]
I'm facing  the same problem, when I try to run your example I get this error:

`INFO:root:searchterm: https://www.google.de/search?tbm=map&tch=1&q=Gran+Morsi+22+Warren+St%2C+New+York%2C+NY+10007%2C+USA&pb=!4m12!1m3!1d4005.9771522653964!2d-122.42072974863942!3d37.8077459796541!2m3!1f0!2f0!3f0!3m2!1i1125!2i976!4f13.1!7i20!10b1!12m6!2m3!5m1!6e2!20e3!10b1!16b1!19m3!2m2!1i392!2i106!20m61!2m2!1i203!2i100!3m2!2i4!5b1!6m6!1m2!1i86!2i86!1m2!1i408!2i200!7m46!1m3!1e1!2b0!3e3!1m3!1e2!2b1!3e2!1m3!1e2!2b0!3e3!1m3!1e3!2b0!3e3!1m3!1e4!2b0!3e3!1m3!1e8!2b0!3e3!1m3!1e3!2b1!3e2!1m3!1e9!2b1!3e2!1m3!1e10!2b0!3e3!1m3!1e10!2b1!3e2!1m3!1e10!2b0!3e4!2b1!4b1!9b0!22m6!1sa9fVWea_MsX8adX8j8AE%3A1!2zMWk6Mix0OjExODg3LGU6MSxwOmE5ZlZXZWFfTXNYOGFkWDhqOEFFOjE!7e81!12e3!17sa9fVWea_MsX8adX8j8AE%3A564!18e15!24m15!2b1!5m4!2b1!3b1!5b1!6b1!10m1!8e3!17b1!24b1!25b1!26b1!30m1!2b1!36b1!26m3!2m2!1i80!2i92!30m28!1m6!1m2!1i0!2i0!2m2!1i458!2i976!1m6!1m2!1i1075!2i0!2m2!1i1125!2i976!1m6!1m2!1i0!2i0!2m2!1i1125!2i20!1m6!1m2!1i0!2i956!2m2!1i1125!2i976!37m1!1e81!42b1!47m0!49m1!3b1`

I've already tried to reinstall it but still not working.

**Comment by raffie-** [comment]
Hi @m-wrzr ,

After re-installing, I still face the same issue. This time around, populartimes.get_id does not work too and gives the following error:


Traceback (most recent call last):

  File "<ipython-input-5-ad07f742cf5e>", line 1, in <module>
    populartimes.get_id(API_KEY1, 'ChIJSYuuSx9awokRyrrOFTGg0GY')

  File "C:\Anaconda3\envs\google_api\lib\site-packages\populartimes\__init__.py", line 53, in get_id
    return get_current_popular_times(api_key, place_id)

  File "C:\Anaconda3\envs\google_api\lib\site-packages\populartimes\crawler.py", line 334, in get_current_popular_times
    rating, rating_n, popularity, current_popularity = get_current_popularity(place_identifier)

  File "C:\Anaconda3\envs\google_api\lib\site-packages\populartimes\crawler.py", line 295, in get_current_popularity
    jdata = json.loads(data)["d"]

  File "C:\Anaconda3\envs\google_api\lib\json\__init__.py", line 319, in loads
    return _default_decoder.decode(s)

  File "C:\Anaconda3\envs\google_api\lib\json\decoder.py", line 342, in decode
    raise JSONDecodeError("Extra data", s, end)

JSONDecodeError: Extra data

**Comment by raffie-** [comment]
@m-wrzr  Hey after updating the package it's working now for me. Thanks!
