### ISSUE TITLE
Result limit in search radius reached and then error `500`

### ISSUE THREAD

**Issue by hassaan-dev** [m-wrzr/populartimes#89]
Hi,

I am using flask to create sample app for testing purpose. `get_id` works fine for me. When I try `get` method in my debug logs on console, I am getting this error

>WARNING:root:Result limit in search radius reached, some data may get lost
WARNING:root:Result limit in search radius reached, some data may get lost
WARNING:root:Result limit in search radius reached, some data may get lost
WARNING:root:Result limit in search radius reached, some data may get lost
WARNING:root:Result limit in search radius reached, some data may get lost
WARNING:root:Result limit in search radius reached, some data may get lost
WARNING:root:Result limit in search radius reached, some data may get lost
WARNING:root:Result limit in search radius reached, some data may get lost
WARNING:root:Result limit in search radius reached, some data may get lost
WARNING:root:Result limit in search radius reached, some data may get lost
WARNING:root:Result limit in search radius reached, some data may get lost
WARNING:root:Result limit in search radius reached, some data may get lost
WARNING:root:Result limit in search radius reached, some data may get lost
WARNING:root:Result limit in search radius reached, some data may get lost
WARNING:root:Result limit in search radius reached, some data may get lost
WARNING:root:Result limit in search radius reached, some data may get lost
WARNING:root:Result limit in search radius reached, some data may get lost
WARNING:root:Result limit in search radius reached, some data may get lost
WARNING:root:Result limit in search radius reached, some data may get lost
`

and after his there is `500` error

>[09/Apr/2020 14:23:29] "GET /get_location?place_type=bar&lat=48.132986&lng=11.566126 HTTP/1.1" 500 -
INFO:werkzeug - - [09/Apr/2020 14:23:29] "GET /get_location?place_type=bar&lat=48.132986&lng=11.566126 HTTP/1.1" 500 -

>Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2131, in make_response
    " {rv.__class__.__name__}.".format(rv=rv)
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a list.

**Comment by hassaan-dev** [comment]
I was giving `["bar"]` as string instead of array
